//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stackstay
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomsHotel
    {
        public int id { get; set; }
        public string RoomName { get; set; }
        public int IdCity { get; set; }
        public int IdBedType { get; set; }
        public int Price { get; set; }
        public byte[] Photo { get; set; }
        public int RoomNumber { get; set; }
        public string IsFree { get; set; }
    
        public virtual BedType BedType { get; set; }
        public virtual Cities Cities { get; set; }
    }
}
